extends Node

@warning_ignore("unused_signal")
signal enemy_damaged(monster_id, hit)
@warning_ignore("unused_signal")
signal enemy_defeated(monster_id, hit)
@warning_ignore("unused_signal")
signal ally_defeated()
@warning_ignore("unused_signal")
signal magic_used(spell_data)
@warning_ignore("unused_signal")
signal ability_used(spell_data)
@warning_ignore("unused_signal")
signal item_used(item_id)
@warning_ignore("unused_signal")
signal limitburst_used(lb_id)
@warning_ignore("unused_signal")
signal esper_evoked(esper_id)
@warning_ignore("unused_signal")
signal mission_completed(party_data, turn_count)
